## 1. Which base image do you want to use?


## 2. Set the working directory inside the container.


## 3. Copy a list of your dependencies to to your working directory.


## 4. Copy the rest of your application's source code.


## 5. Make PORT 8080 available to the world outside the running container


## 6. Define the command to run when the container starts.