version: '3.3'
services:
  db:
    image:            # The Docker image to use for the PostgreSQL service
    restart: always   # The restart policy for the container (e.g., always, on-failure, etc.)
    environment:      # Environment variables passed into the PostgreSQL container 
                      # (Database name, user, and password can be initialized here – See the docker docs for PostgreSQL)
    ports:            # Port mapping between the host and the container
    volumes:          # Volumes to be mounted in the container, used for data persistence

  app:
    image:            # The Docker image to use for the Flask application service
    restart: always   # The restart policy for the container (e.g., always, on-failure, etc.)
    ports:            # Port mapping between the host and the container

volumes:
  # Define named volumes here. This named volume is used for persistent storage of PostgreSQL data