version: '3.3'
services:
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: 'db'        
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports: 
      - '3306:3306'
    volumes: # Volumes to be mounted in the container, used for data persistence

  app:
    image: # your image here
    depends_on: db
    environment:
      DATABASE: 'db'
      USER: 'user'
      PASSWORD: 'password'
    ports: 
      - '8080:8080'     

volumes:
   # Define named volumes here. These volumes can be used by services for persistent storage
